import Head from 'next/head';

import Hero from '../components/Hero';
import Headline from '../components/Headline';

export default function Home() {
  return (
    <>
      <Head>
        <title>Imersão Asas | Dayane Silva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero>
        <Headline>
          <h1>
            Descubra como{' '}
            <strong>criar conteúdo de forma estratégica e intencional</strong>,
            usando o poder da sua marca pessoal e posicionamento para vender
            mais!
          </h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur,
            suscipit. Distinctio aliquam corporis mollitia dolor doloremque,
            illo libero recusandae officiis. Et dolore, quos praesentium quaerat
            ullam fugit assumenda tempora laudantium.
          </p>
          <form
            id="sib-form"
            method="POST"
            action="https://04c4e6f3.sibforms.com/serve/MUIEAFjnDl_2LPLWdoUIZlAQH_J-kjaneoaCdlolC-UaeteRenTCTUBTb5jCsjgzXgcV_T2Ixja5whB-SuvWrdPWvteDbaaq5xIWhnhvUfHPFSKCxGncmQBMc5swekj8oAYaO3PXqZ4dKXJchKgOz35xdeEVTApiYKlETMB7ESObGlJs2n2Qd6rIBOdGps36fSGhmOpew7IhUn29"
          >
            <input
              type="email"
              id="EMAIL"
              name="EMAIL"
              placeholder="EMAIL"
              data-required="true"
              required
            />
            <button form="sib-form" type="submit">
              Quero mais detalhes da Imersão
            </button>
            <input type="hidden" name="locale" value="pt" />
            <input type="hidden" name="html_type" value="simple" />
          </form>
        </Headline>
      </Hero>
    </>
  );
}
